/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.reto2;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Administrador
 */
public class BongoLoadingScreen extends javax.swing.JFrame {

    /**
     * Creates new form BongoLoadingScreen
     */
    public BongoLoadingScreen() {
        initComponents();
        setLocationRelativeTo(null);
        addLogo();
        jLabelLoadingText.setText("loading...");
    }
    
    public void addLogo() {
        try {
        URL imageUrl = getClass().getResource("/images/logoEnd.png");
        if (imageUrl == null) {
            throw new IllegalArgumentException("¡Imagen no encontrada!");
        }
        Image image = ImageIO.read(imageUrl);
        JPanel imagePanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (image != null) {
                    g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };
        imagePanel.setPreferredSize(jPanelLogoBongoPhoto3.getPreferredSize());
        jPanelLogoBongoPhoto3.setLayout(new BorderLayout());
        jPanelLogoBongoPhoto3.removeAll();
        jPanelLogoBongoPhoto3.add(imagePanel, BorderLayout.CENTER);
        jPanelLogoBongoPhoto3.revalidate();
        jPanelLogoBongoPhoto3.repaint();
    } catch (Exception ex) {
        ex.printStackTrace();
        }
    }
    
    public void showLoadingScreen() {
        BongoLoadingScreen bongoLoadingScreen = new BongoLoadingScreen();
        bongoLoadingScreen.setVisible(true);
        bongoLoadingScreen.setAlwaysOnTop(true);
        Timer timer = new Timer(1400, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                bongoLoadingScreen.setVisible(false);
                ((Timer)e.getSource()).stop();
            }
        });
        timer.setRepeats(false);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogoBongoPhoto3 = new javax.swing.JPanel();
        jLabelLoadingText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));

        javax.swing.GroupLayout jPanelLogoBongoPhoto3Layout = new javax.swing.GroupLayout(jPanelLogoBongoPhoto3);
        jPanelLogoBongoPhoto3.setLayout(jPanelLogoBongoPhoto3Layout);
        jPanelLogoBongoPhoto3Layout.setHorizontalGroup(
            jPanelLogoBongoPhoto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanelLogoBongoPhoto3Layout.setVerticalGroup(
            jPanelLogoBongoPhoto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        jLabelLoadingText.setText("loading...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogoBongoPhoto3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabelLoadingText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLogoBongoPhoto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelLoadingText)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BongoLoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BongoLoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BongoLoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BongoLoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BongoLoadingScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLoadingText;
    private javax.swing.JPanel jPanelLogoBongoPhoto3;
    // End of variables declaration//GEN-END:variables
}
