/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.reto2;

import java.util.ArrayList;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author profesor3
 */
public class EditContactData extends javax.swing.JFrame {

    /**
     * Creates new form EditEmpresaData
     */
    public EditContactData() {
        initComponents();
        setLocationRelativeTo(null);
        setUpContactList();
        setupEventListeners();
    }

    public void setUpContactList() {
        MyConnection conexion = new MyConnection();
        List<String> dataList = conexion.contactList();

        jListContacts.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = dataList.toArray(new String[0]);

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }

    private void setupEventListeners() {
        jListContacts.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedContact = getSelectedContactIndex();
                    String selectedContactData = getSelectedContactData(selectedContact);
                    displayContactData(selectedContactData);
                }
            }
        });
    }

    private int getSelectedContactIndex() {
        return jListContacts.getSelectedIndex();
    }

    private String getSelectedContactData(int index) {
        if (index != -1) {
            MyConnection connection = new MyConnection();
            List<String> dataList = connection.companyData(index);
            return dataList.isEmpty() ? "" : dataList.get(0);
        }
        return "";
    }

    public void displayContactData(String data) {
        if (data != null && !data.isEmpty()) {
            String[] values = data.split(", ");
            if (values.length >= 3) {
                setTextFields(values);
            } else {
                setUnknownTextFields();
            }
        }
    }

    private void setTextFields(String[] values) {
        jTextFieldICompanyName.setText(values[0]);
        jTextFieldTeacherName.setText(values[1]);
        jTextFieldContactName.setText(values[2]);
        jTextFieldContactJob.setText(values[3]);
    }

    private void setUnknownTextFields() {
        jTextFieldICompanyName.setText("Unknown");
        jTextFieldTeacherName.setText("Unknown");
        jTextFieldContactName.setText("Unknown");
        jTextFieldContactJob.setText("Unknown");
    }

    public void reloadWindow() {
        jTextFieldICompanyName.setText("");
        jTextFieldTeacherName.setText("");
        jTextFieldContactName.setText("");
        jTextFieldContactJob.setText("");
        setUpContactList();
        setupEventListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListContacts = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabelCompany = new javax.swing.JLabel();
        jTextFieldICompanyName = new javax.swing.JTextField();
        jLabelSector = new javax.swing.JLabel();
        jTextFieldTeacherName = new javax.swing.JTextField();
        jLabelFTCs = new javax.swing.JLabel();
        jTextFieldContactName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldContactJob = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListContacts.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListContacts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListContacts.setToolTipText("");
        jListContacts.setPreferredSize(new java.awt.Dimension(25, 90));
        jScrollPane1.setViewportView(jListContacts);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setPreferredSize(new java.awt.Dimension(25, 90));

        jLabelCompany.setText("Company");

        jTextFieldICompanyName.setText("Unknown");
        jTextFieldICompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldICompanyNameActionPerformed(evt);
            }
        });

        jLabelSector.setText("Teacher Name:");

        jTextFieldTeacherName.setText("Unknown");
        jTextFieldTeacherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTeacherNameActionPerformed(evt);
            }
        });

        jLabelFTCs.setText("Contact Name");

        jTextFieldContactName.setText("Unknown");
        jTextFieldContactName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContactNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Contact Job");

        jTextFieldContactJob.setText("Unknown");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldICompanyName)
                    .addComponent(jTextFieldTeacherName)
                    .addComponent(jTextFieldContactName)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCompany)
                            .addComponent(jLabelSector)
                            .addComponent(jLabelFTCs)
                            .addComponent(jLabel1))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addComponent(jTextFieldContactJob))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCompany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldICompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFTCs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldContactName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldContactJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldICompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldICompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldICompanyNameActionPerformed

    private void jTextFieldTeacherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTeacherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTeacherNameActionPerformed

    private void jTextFieldContactNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContactNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContactNameActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditContactData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditContactData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditContactData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditContactData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditContactData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCompany;
    private javax.swing.JLabel jLabelFTCs;
    private javax.swing.JLabel jLabelSector;
    private javax.swing.JList<String> jListContacts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldContactJob;
    private javax.swing.JTextField jTextFieldContactName;
    private javax.swing.JTextField jTextFieldICompanyName;
    private javax.swing.JTextField jTextFieldTeacherName;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
