/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.reto2;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/**
 *
 * @author ol1ve
 */
public class LoadingScreen extends javax.swing.JPanel {

    /**
     * Creates new form LoadingScreen
     */
    public LoadingScreen() {
        initComponents();
        addLogo();
    }
    public void addLogo() {
        try {
        URL imageUrl = getClass().getResource("/images/logoEnd.png");
        if (imageUrl == null) {
            throw new IllegalArgumentException("¡Imagen no encontrada!");
        }
        Image image = ImageIO.read(imageUrl);
        JPanel imagePanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (image != null) {
                    g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };
        imagePanel.setPreferredSize(jPanelLogoBongoPhoto3.getPreferredSize());
        jPanelLogoBongoPhoto3.setLayout(new BorderLayout());
        jPanelLogoBongoPhoto3.removeAll();
        jPanelLogoBongoPhoto3.add(imagePanel, BorderLayout.CENTER);
        jPanelLogoBongoPhoto3.revalidate();
        jPanelLogoBongoPhoto3.repaint();
    } catch (Exception ex) {
        ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogoBongoPhoto3 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanelLogoBongoPhoto3Layout = new javax.swing.GroupLayout(jPanelLogoBongoPhoto3);
        jPanelLogoBongoPhoto3.setLayout(jPanelLogoBongoPhoto3Layout);
        jPanelLogoBongoPhoto3Layout.setHorizontalGroup(
            jPanelLogoBongoPhoto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        jPanelLogoBongoPhoto3Layout.setVerticalGroup(
            jPanelLogoBongoPhoto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogoBongoPhoto3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogoBongoPhoto3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelLogoBongoPhoto3;
    // End of variables declaration//GEN-END:variables
}
